version: "2"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=8081 
    volumes:
      - ./var/qBittorrent/config:/config 
      - ./var/qBittorrent/downloads:/downloads 
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8081:8081
    restart: unless-stopped
    networks:
      animeNetwork:
        ipv4_address: 172.172.0.2
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: auto_anime
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./var/mysql/data:/var/lib/mysql
      - ./var/mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./var/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
    networks:
      animeNetwork:
        ipv4_address: 172.172.0.3
  autoanime:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoAnime
    ports:
      - 5555:5555
    volumes:
      - .var/autoAnime :/autoAnime
      - ./log :/autoAnime/log
      - ./seed :/autoAnime/seed
    depends_on:
      - mysql
      - qbittorrent
    networks:
      animeNetwork:
        ipv4_address: 172.172.0.4

networks:
  animeNetwork:
    ipam:
      config:
        - subnet: 172.172.0.0/16