"""empty message

Revision ID: 1d533eaeaba0
Revises: 4bf2736b65b0
Create Date: 2023-09-15 17:06:45.238451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d533eaeaba0'
down_revision = '4bf2736b65b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_seed',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mikan_id', sa.Integer(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('seed_name', sa.String(length=200), nullable=False),
    sa.Column('seed_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('seed_url')
    )
    with op.batch_alter_table('anime_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anime_type', sa.Integer(), nullable=True, comment='0为番剧,1为剧场版,2为ova'))
        batch_op.add_column(sa.Column('subscribe_status', sa.Integer(), nullable=True, comment='0为未订阅,1为已订阅'))
        batch_op.alter_column('mikan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('update_day',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='剧场版和ova为0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_list', schema=None) as batch_op:
        batch_op.alter_column('update_day',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='剧场版和ova为0')
        batch_op.alter_column('mikan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('subscribe_status')
        batch_op.drop_column('anime_type')

    op.drop_table('anime_seed')
    # ### end Alembic commands ###
