"""empty message

Revision ID: 2f9c9044a9e2
Revises: b53c3c97a47f
Create Date: 2023-09-15 18:10:38.980852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9c9044a9e2'
down_revision = 'b53c3c97a47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_list',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anime_name', sa.String(length=40), nullable=True),
    sa.Column('mikan_id', sa.Integer(), nullable=True),
    sa.Column('update_day', sa.Integer(), nullable=True, comment='剧场版和ova为0'),
    sa.Column('img_url', sa.String(length=40), nullable=False),
    sa.Column('anime_type', sa.Integer(), nullable=True, comment='0为番剧,1为剧场版,2为ova'),
    sa.Column('subscribe_status', sa.Integer(), nullable=True, comment='0为未订阅,1为已订阅'),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('anime_name'),
    sa.UniqueConstraint('mikan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_list')
    # ### end Alembic commands ###
