"""empty message

Revision ID: 3fe680249872
Revises: 
Create Date: 2023-09-20 21:32:59.686183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fe680249872'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_seed',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mikan_id', sa.Integer(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('seed_name', sa.String(length=200), nullable=False),
    sa.Column('seed_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('seed_url')
    )
    op.create_table('anime_task',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mikan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True, comment='下载的状态 0表示还没有开始下载 1表示下载成功 2表示下载开始但是过程失败'),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('torrent_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    with op.batch_alter_table('anime_list', schema=None) as batch_op:
        batch_op.alter_column('anime_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=40),
               nullable=True)
        batch_op.alter_column('mikan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('update_day',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='剧场版和ova为8')
        batch_op.alter_column('anime_type',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='0为番剧,1为剧场版,2为ova')
        batch_op.alter_column('subscribe_status',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='0为未订阅,1为已订阅')
        batch_op.create_unique_constraint(None, ['anime_name'])
        batch_op.create_unique_constraint(None, ['mikan_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('subscribe_status',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='0为未订阅,1为已订阅')
        batch_op.alter_column('anime_type',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='0为番剧,1为剧场版,2为ova')
        batch_op.alter_column('update_day',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='剧场版和ova为8')
        batch_op.alter_column('mikan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('anime_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=40),
               nullable=False)

    op.drop_table('anime_task')
    op.drop_table('anime_seed')
    # ### end Alembic commands ###
