"""empty message

Revision ID: 4bf2736b65b0
Revises: bc959ab6dafa
Create Date: 2023-09-13 20:31:25.756427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf2736b65b0'
down_revision = 'bc959ab6dafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_seed',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mikan_id', sa.Integer(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('seed_name', sa.String(length=200), nullable=False),
    sa.Column('seed_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('seed_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_seed')
    # ### end Alembic commands ###
