"""empty message

Revision ID: 4f46f4dfcb0c
Revises: a69f282c0435
Create Date: 2023-09-17 15:20:11.547700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f46f4dfcb0c'
down_revision = 'a69f282c0435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_list', schema=None) as batch_op:
        batch_op.alter_column('update_day',
               existing_type=mysql.INTEGER(),
               comment='剧场版和ova为8',
               existing_comment='剧场版和ova为0',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_list', schema=None) as batch_op:
        batch_op.alter_column('update_day',
               existing_type=mysql.INTEGER(),
               comment='剧场版和ova为0',
               existing_comment='剧场版和ova为8',
               existing_nullable=True)

    # ### end Alembic commands ###
