"""empty message

Revision ID: 6ea2e15eab47
Revises: b3ddd6a934ba
Create Date: 2023-09-17 00:35:26.854933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea2e15eab47'
down_revision = 'b3ddd6a934ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('torrent_name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_task', schema=None) as batch_op:
        batch_op.drop_column('torrent_name')

    # ### end Alembic commands ###
