"""empty message

Revision ID: 7af8185d42fc
Revises: b0171c73fc74
Create Date: 2023-09-13 17:36:34.626740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af8185d42fc'
down_revision = 'b0171c73fc74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_seed', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['seed_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_seed', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
