"""empty message

Revision ID: 9d929e301cb5
Revises: 
Create Date: 2023-09-12 18:27:05.846824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d929e301cb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_list',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anime_name', sa.String(length=40), nullable=True),
    sa.Column('mikan_id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=40), nullable=False),
    sa.Column('update_day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('anime_name'),
    sa.UniqueConstraint('mikan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_list')
    # ### end Alembic commands ###
