"""empty message

Revision ID: a69f282c0435
Revises: 6ea2e15eab47
Create Date: 2023-09-17 00:54:17.581973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69f282c0435'
down_revision = '6ea2e15eab47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_task', schema=None) as batch_op:
        batch_op.drop_index('mikan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_task', schema=None) as batch_op:
        batch_op.create_index('mikan_id', ['mikan_id'], unique=False)

    # ### end Alembic commands ###
