"""empty message

Revision ID: b0171c73fc74
Revises: bacf00afae7a
Create Date: 2023-09-13 17:21:17.103576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0171c73fc74'
down_revision = 'bacf00afae7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_seed', schema=None) as batch_op:
        batch_op.drop_index('episode')
        batch_op.drop_index('mikan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_seed', schema=None) as batch_op:
        batch_op.create_index('mikan_id', ['mikan_id'], unique=False)
        batch_op.create_index('episode', ['episode'], unique=False)

    # ### end Alembic commands ###
