"""empty message

Revision ID: b3ddd6a934ba
Revises: 2f9c9044a9e2
Create Date: 2023-09-16 21:38:35.517814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3ddd6a934ba'
down_revision = '2f9c9044a9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mikan_id', sa.Integer(), nullable=False))
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='下载的状态 0表示还没有开始下载 1表示下载成功 2表示下载开始但是过程失败',
               existing_nullable=True)
        batch_op.alter_column('episode',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=40),
               type_=sa.Integer(),
               nullable=False)
        batch_op.drop_index('anime_id')
        batch_op.create_unique_constraint(None, ['mikan_id'])
        batch_op.drop_column('anime_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anime_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('anime_id', ['anime_id'], unique=False)
        batch_op.alter_column('episode',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=40),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='下载的状态 0表示还没有开始下载 1表示下载成功 2表示下载开始但是过程失败',
               existing_nullable=True)
        batch_op.drop_column('mikan_id')

    # ### end Alembic commands ###
