"""empty message

Revision ID: bacf00afae7a
Revises: b0a4987e6cf7
Create Date: 2023-09-13 17:12:46.155696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacf00afae7a'
down_revision = 'b0a4987e6cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_list',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anime_name', sa.String(length=40), nullable=True),
    sa.Column('mikan_id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=40), nullable=False),
    sa.Column('update_day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('anime_name'),
    sa.UniqueConstraint('mikan_id')
    )
    op.create_table('anime_seed',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mikan_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('seed_url', sa.String(length=200), nullable=False),
    sa.Column('subgroup', sa.String(length=40), nullable=False),
    sa.Column('seed_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('episode'),
    sa.UniqueConstraint('mikan_id')
    )
    op.create_table('anime_task',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('episode', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('anime_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_task')
    op.drop_table('anime_seed')
    op.drop_table('anime_list')
    # ### end Alembic commands ###
