"""empty message

Revision ID: bc959ab6dafa
Revises: efc5ca9eeb2e
Create Date: 2023-09-13 20:11:07.035893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc959ab6dafa'
down_revision = 'efc5ca9eeb2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_seed',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mikan_id', sa.Integer(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('seed_name', sa.String(length=200), nullable=False),
    sa.Column('seed_url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('seed_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_seed')
    # ### end Alembic commands ###
